name: Close Pull Requests
on:
  pull_request_target:
    types: [opened]
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "This showcase repo doesn’t accept pull requests."
